"""
Copyright (C) 2010 - 2013 TopCoder Inc., All Rights Reserved.

This module specifies configurable details of the parser including
numerical/logical/textual attribute names and CMS codes, numerical
operators, digits, and characters.

This module also specifies how numerical operators are translated to SQL.

@version 1.0 (Healthcare Fraud Prevention - Query Parsing and Query Generation)
@author: TCSASSEMBLER
"""
class ParserConfig:
    """
    The Parser class should extend this class to access specified configuration.
    """
    # Edit numerical_attributes to adapt to new set of numerical attributes.
    numerical_attributes = [
        # Beneficiaries
        ("'End stage renal disease Indicator'", "BENE_ESRD_IND"),
        ("'Date of Birth'", "BENE_BIRTH_DT"),
        ("'Date of Death'", "BENE_DEATH_DT"),
        ("'Sex'", "BENE_SEX_IDENT_CD"),
        ("'Beneficiary Race Code'", "BENE_RACE_CD"),
        ("'Total number of months of part A coverage for the beneficiary'", "BENE_HI_CVRAGE_TOT_MONS"),
        ("'Total number of months of part B coverage for the beneficiary'", "BENE_SMI_CVRAGE_TOT_MONS"),
        ("'Total number of months of HMO coverage for the beneficiary'", "BENE_HMO_CVRAGE_TOT_MONS"),
        ("'Total number of months of part D plan coverage for the beneficiary'", "PLAN_CVRG_MOS_NUM"),
        ("'Inpatient annual Medicare reimbursement amount'", "MEDREIMB_IP"),
        ("'Inpatient annual beneficiary responsibility amount'", "BENRES_IP"),
        ("'Inpatient annual primary payer reimbursement amount'", "PPPYMT_IP"),
        ("'Outpatient annual Medicare reimbursement amount'", "MEDREIMB_OP"),
        ("'Outpatient annual beneficiary responsibility amount'", "BENRES_OP"),
        ("'Outpatient annual primary payer reimbursement amount'", "PPPYMT_OP"),
        ("'Carrier annual Medicare reimbursement amount'", "MEDREIMB_CAR"),
        ("'Carrier annual beneficiary responsibility amount'", "BENRES_CAR"),
        ("'Carrier annual primary payer reimbursement amount'", "PPPYMT_CAR"),
        # Carriers
        ("'Claim start date'", "CLM_FROM_DT"),
        ("'Claim end date'", "CLM_THRU_DT"),
        ("'Line NCH Payment Amount 1'", "LINE_NCH_PMT_AMT_1"),
        ("'Line NCH Payment Amount 2'", "LINE_NCH_PMT_AMT_2"),
        ("'Line NCH Payment Amount 3'", "LINE_NCH_PMT_AMT_3"),
        ("'Line NCH Payment Amount 4'", "LINE_NCH_PMT_AMT_4"),
        ("'Line NCH Payment Amount 5'", "LINE_NCH_PMT_AMT_5"),
        ("'Line NCH Payment Amount 6'", "LINE_NCH_PMT_AMT_6"),
        ("'Line NCH Payment Amount 7'", "LINE_NCH_PMT_AMT_7"),
        ("'Line NCH Payment Amount 8'", "LINE_NCH_PMT_AMT_8"),
        ("'Line NCH Payment Amount 9'", "LINE_NCH_PMT_AMT_9"),
        ("'Line NCH Payment Amount 10'", "LINE_NCH_PMT_AMT_10"),
        ("'Line NCH Payment Amount 11'", "LINE_NCH_PMT_AMT_11"),
        ("'Line NCH Payment Amount 12'", "LINE_NCH_PMT_AMT_12"),
        ("'Line NCH Payment Amount 13'", "LINE_NCH_PMT_AMT_13"),
        ("'Line Beneficiary Part B Deductible Amount 1'", "LINE_BENE_PTB_DDCTBL_AMT_1"),
        ("'Line Beneficiary Part B Deductible Amount 2'", "LINE_BENE_PTB_DDCTBL_AMT_2"),
        ("'Line Beneficiary Part B Deductible Amount 3'", "LINE_BENE_PTB_DDCTBL_AMT_3"),
        ("'Line Beneficiary Part B Deductible Amount 4'", "LINE_BENE_PTB_DDCTBL_AMT_4"),
        ("'Line Beneficiary Part B Deductible Amount 5'", "LINE_BENE_PTB_DDCTBL_AMT_5"),
        ("'Line Beneficiary Part B Deductible Amount 6'", "LINE_BENE_PTB_DDCTBL_AMT_6"),
        ("'Line Beneficiary Part B Deductible Amount 7'", "LINE_BENE_PTB_DDCTBL_AMT_7"),
        ("'Line Beneficiary Part B Deductible Amount 8'", "LINE_BENE_PTB_DDCTBL_AMT_8"),
        ("'Line Beneficiary Part B Deductible Amount 9'", "LINE_BENE_PTB_DDCTBL_AMT_9"),
        ("'Line Beneficiary Part B Deductible Amount 10'", "LINE_BENE_PTB_DDCTBL_AMT_10"),
        ("'Line Beneficiary Part B Deductible Amount 11'", "LINE_BENE_PTB_DDCTBL_AMT_11"),
        ("'Line Beneficiary Part B Deductible Amount 12'", "LINE_BENE_PTB_DDCTBL_AMT_12"),
        ("'Line Beneficiary Part B Deductible Amount 13'", "LINE_BENE_PTB_DDCTBL_AMT_13"),
        ("'Line Beneficiary Primary Payer Paid Amount 1'", "LINE_BENE_PRMRY_PYR_PD_AMT_1"),
        ("'Line Beneficiary Primary Payer Paid Amount 2'", "LINE_BENE_PRMRY_PYR_PD_AMT_2"),
        ("'Line Beneficiary Primary Payer Paid Amount 3'", "LINE_BENE_PRMRY_PYR_PD_AMT_3"),
        ("'Line Beneficiary Primary Payer Paid Amount 4'", "LINE_BENE_PRMRY_PYR_PD_AMT_4"),
        ("'Line Beneficiary Primary Payer Paid Amount 5'", "LINE_BENE_PRMRY_PYR_PD_AMT_5"),
        ("'Line Beneficiary Primary Payer Paid Amount 6'", "LINE_BENE_PRMRY_PYR_PD_AMT_6"),
        ("'Line Beneficiary Primary Payer Paid Amount 7'", "LINE_BENE_PRMRY_PYR_PD_AMT_7"),
        ("'Line Beneficiary Primary Payer Paid Amount 8'", "LINE_BENE_PRMRY_PYR_PD_AMT_8"),
        ("'Line Beneficiary Primary Payer Paid Amount 9'", "LINE_BENE_PRMRY_PYR_PD_AMT_9"),
        ("'Line Beneficiary Primary Payer Paid Amount 10'", "LINE_BENE_PRMRY_PYR_PD_AMT_10"),
        ("'Line Beneficiary Primary Payer Paid Amount 11'", "LINE_BENE_PRMRY_PYR_PD_AMT_11"),
        ("'Line Beneficiary Primary Payer Paid Amount 12'", "LINE_BENE_PRMRY_PYR_PD_AMT_12"),
        ("'Line Beneficiary Primary Payer Paid Amount 13'", "LINE_BENE_PRMRY_PYR_PD_AMT_13"),
        ("'Line Coinsurance Amount 1'", "LINE_COINSRNC_AMT_1"),
        ("'Line Coinsurance Amount 2'", "LINE_COINSRNC_AMT_2"),
        ("'Line Coinsurance Amount 3'", "LINE_COINSRNC_AMT_3"),
        ("'Line Coinsurance Amount 4'", "LINE_COINSRNC_AMT_4"),
        ("'Line Coinsurance Amount 5'", "LINE_COINSRNC_AMT_5"),
        ("'Line Coinsurance Amount 6'", "LINE_COINSRNC_AMT_6"),
        ("'Line Coinsurance Amount 7'", "LINE_COINSRNC_AMT_7"),
        ("'Line Coinsurance Amount 8'", "LINE_COINSRNC_AMT_8"),
        ("'Line Coinsurance Amount 9'", "LINE_COINSRNC_AMT_9"),
        ("'Line Coinsurance Amount 10'", "LINE_COINSRNC_AMT_10"),
        ("'Line Coinsurance Amount 11'", "LINE_COINSRNC_AMT_11"),
        ("'Line Coinsurance Amount 12'", "LINE_COINSRNC_AMT_12"),
        ("'Line Coinsurance Amount 13'", "LINE_COINSRNC_AMT_13"),
        ("'Line Allowed Charge Amount 1'", "LINE_ALOWD_CHRG_AMT_1"),
        ("'Line Allowed Charge Amount 2'", "LINE_ALOWD_CHRG_AMT_2"),
        ("'Line Allowed Charge Amount 3'", "LINE_ALOWD_CHRG_AMT_3"),
        ("'Line Allowed Charge Amount 4'", "LINE_ALOWD_CHRG_AMT_4"),
        ("'Line Allowed Charge Amount 5'", "LINE_ALOWD_CHRG_AMT_5"),
        ("'Line Allowed Charge Amount 6'", "LINE_ALOWD_CHRG_AMT_6"),
        ("'Line Allowed Charge Amount 7'", "LINE_ALOWD_CHRG_AMT_7"),
        ("'Line Allowed Charge Amount 8'", "LINE_ALOWD_CHRG_AMT_8"),
        ("'Line Allowed Charge Amount 9'", "LINE_ALOWD_CHRG_AMT_9"),
        ("'Line Allowed Charge Amount 10'", "LINE_ALOWD_CHRG_AMT_10"),
        ("'Line Allowed Charge Amount 11'", "LINE_ALOWD_CHRG_AMT_11"),
        ("'Line Allowed Charge Amount 12'", "LINE_ALOWD_CHRG_AMT_12"),
        ("'Line Allowed Charge Amount 13'", "LINE_ALOWD_CHRG_AMT_13"),
        # Inpatients
        ("'Claim Line Segment'", "SEGMENT"),
        ("'Claims start date'", "CLM_FROM_DT"),
        ("'Claims end date'", "CLM_THRU_DT"),
        ("'Claim Payment Amount'", "CLM_PMT_AMT"),
        ("'NCH Primary Payer Claim Paid Amount'", "NCH_PRMRY_PYR_CLM_PD_AMT"),
        ("'Inpatient admission date'", "CLM_ADMSN_DT"),
        ("'Claim Pass Thru Per Diem Amount'", "CLM_PASS_THRU_PER_DIEM_AMT"),
        ("'NCH Beneficiary Inpatient Deductible Amount'", "NCH_BENE_IP_DDCTBL_AMT"),
        ("'NCH Beneficiary Part A Coinsurance Liability Amount'", "NCH_BENE_PTA_COINSRNC_LBLTY_AM"),
        ("'NCH Beneficiary Blood Deductible Liability Amount'", "NCH_BENE_BLOOD_DDCTBL_LBLTY_AM"),
        ("'Claim Utilization Day Count'", "CLM_UTLZTN_DAY_CNT"),
        ("'Inpatient discharged date'", "NCH_BENE_DSCHRG_DT"),
        # Outpatients
        ("'Claim Line Segment'", "SEGMENT"),
        ("'Claims start date'", "CLM_FROM_DT"),
        ("'Claims end date'", "CLM_THRU_DT"),
        ("'Claim Payment Amount'", "CLM_PMT_AMT"),
        ("'NCH Primary Payer Claim Paid Amount'", "NCH_PRMRY_PYR_CLM_PD_AMT"),
        ("'NCH Beneficiary Blood Deductible Liability Amount'", "NCH_BENE_BLOOD_DDCTBL_LBLTY_AM"),
        ("'NCH Beneficiary Part B Deductible Amount'", "NCH_BENE_PTB_DDCTBL_AMT"),
        ("'NCH Beneficiary Part B Coinsurance Amount'", "NCH_BENE_PTB_COINSRNC_AMT"),
        # Prescription
        ("'RX Service Date'", "SRVC_DT"),
        ("'Quantity Dispensed'", "QTY_DSPNSD_NUM"),
        ("'Days Supply'", "DAYS_SUPLY_NUM"),
        ("'Patient Pay Amount'", "PTNT_PAY_AMT"),
        ("'Gross Drug Cost'", "TOT_RX_CST_AMT"),
    ]

    # Edit logical_attributes to adapt to new set of logical attributes.
    logical_attributes = [
        # Beneficiaries
				("'Chronic Condition: Alzheimer or related disorders or senile'", "SP_ALZHDMTA"),
        ("'Chronic Condition: Heart Failure'", "SP_CHF"),
        ("'Chronic Condition: Chronic Kidney Disease'", "SP_CHRNKIDN"),
        ("'Chronic Condition: Cancer'", "SP_CNCR"),
        ("'Chronic Condition: Chronic Obstructive Pulmonary Disease'", "SP_COPD"),
        ("'Chronic Condition: Depression'", "SP_DEPRESSN"),
        ("'Chronic Condition: Diabetes'", "SP_DIABETES"),
        ("'Chronic Condition: Ischemic Heart Disease'", "SP_ISCHMCHT"),
        ("'Chronic Condition: Osteoporosis'", "SP_OSTEOPRS"),
        ("'Chronic Condition: Rheumatoid Arthritis or Osteoarthritis (RA/OA)'", "SP_RA_OA"),
        ("'Chronic Condition: Stroke/transient Ischemic Attack'", "SP_STRKETIA"),
    ]

    # Edit textual_attributes to adapt to new set of textual attributes.
    textual_attributes = [
    		# Beneficiaries
        #("'End stage renal disease Indicator'", "BENE_ESRD_IND"),
        ("'Beneficiary Code'", "DESYNPUF_ID"),
        ("'State Code'", "SP_STATE_CODE"),
        ("'County Code'", "BENE_COUNTY_CD"),
        # Carriers
        ("'Beneficiary Code'", "DESYNPUF_ID"),
        ("'Claim ID'", "CLM_ID"),
        ("'Claim Diagnosis Code 1'", "ICD9_DGNS_CD_1"),
        ("'Claim Diagnosis Code 2'", "ICD9_DGNS_CD_2"),
        ("'Claim Diagnosis Code 3'", "ICD9_DGNS_CD_3"),
        ("'Claim Diagnosis Code 4'", "ICD9_DGNS_CD_4"),
        ("'Claim Diagnosis Code 5'", "ICD9_DGNS_CD_5"),
        ("'Claim Diagnosis Code 6'", "ICD9_DGNS_CD_6"),
        ("'Claim Diagnosis Code 7'", "ICD9_DGNS_CD_7"),
        ("'Claim Diagnosis Code 8'", "ICD9_DGNS_CD_8"),
        ("'Provider Physician - National Provider Identifier Number 1'", "PRF_PHYSN_NPI_1"),
        ("'Provider Physician - National Provider Identifier Number 2'", "PRF_PHYSN_NPI_2"),
        ("'Provider Physician - National Provider Identifier Number 3'", "PRF_PHYSN_NPI_3"),
        ("'Provider Physician - National Provider Identifier Number 4'", "PRF_PHYSN_NPI_4"),
        ("'Provider Physician - National Provider Identifier Number 5'", "PRF_PHYSN_NPI_5"),
        ("'Provider Physician - National Provider Identifier Number 6'", "PRF_PHYSN_NPI_6"),
        ("'Provider Physician - National Provider Identifier Number 7'", "PRF_PHYSN_NPI_7"),
        ("'Provider Physician - National Provider Identifier Number 8'", "PRF_PHYSN_NPI_8"),
        ("'Provider Physician - National Provider Identifier Number 9'", "PRF_PHYSN_NPI_9"),
        ("'Provider Physician - National Provider Identifier Number 10'", "PRF_PHYSN_NPI_10"),
        ("'Provider Physician - National Provider Identifier Number 11'", "PRF_PHYSN_NPI_11"),
        ("'Provider Physician - National Provider Identifier Number 12'", "PRF_PHYSN_NPI_12"),
        ("'Provider Physician - National Provider Identifier Number 13'", "PRF_PHYSN_NPI_13"),
        ("'Provider Institution Tax Number 1'", "TAX_NUM_1"),
        ("'Provider Institution Tax Number 2'", "TAX_NUM_2"),
        ("'Provider Institution Tax Number 3'", "TAX_NUM_3"),
        ("'Provider Institution Tax Number 4'", "TAX_NUM_4"),
        ("'Provider Institution Tax Number 5'", "TAX_NUM_5"),
        ("'Provider Institution Tax Number 6'", "TAX_NUM_6"),
        ("'Provider Institution Tax Number 7'", "TAX_NUM_7"),
        ("'Provider Institution Tax Number 8'", "TAX_NUM_8"),
        ("'Provider Institution Tax Number 9'", "TAX_NUM_9"),
        ("'Provider Institution Tax Number 10'", "TAX_NUM_10"),
        ("'Provider Institution Tax Number 11'", "TAX_NUM_11"),
        ("'Provider Institution Tax Number 12'", "TAX_NUM_12"),
        ("'Provider Institution Tax Number 13'", "TAX_NUM_13"),
        ("'Line HCFA Common Procedure Coding System 1'", "HCPCS_CD_1"),
        ("'Line HCFA Common Procedure Coding System 2'", "HCPCS_CD_2"),
        ("'Line HCFA Common Procedure Coding System 3'", "HCPCS_CD_3"),
        ("'Line HCFA Common Procedure Coding System 4'", "HCPCS_CD_4"),
        ("'Line HCFA Common Procedure Coding System 5'", "HCPCS_CD_5"),
        ("'Line HCFA Common Procedure Coding System 6'", "HCPCS_CD_6"),
        ("'Line HCFA Common Procedure Coding System 7'", "HCPCS_CD_7"),
        ("'Line HCFA Common Procedure Coding System 8'", "HCPCS_CD_8"),
        ("'Line HCFA Common Procedure Coding System 9'", "HCPCS_CD_9"),
        ("'Line HCFA Common Procedure Coding System 10'", "HCPCS_CD_10"),
        ("'Line HCFA Common Procedure Coding System 11'", "HCPCS_CD_11"),
        ("'Line HCFA Common Procedure Coding System 12'", "HCPCS_CD_12"),
        ("'Line HCFA Common Procedure Coding System 13'", "HCPCS_CD_13"),
        ("'Line Processing Indicator Code 1'", "LINE_PRCSG_IND_CD_1"),
        ("'Line Processing Indicator Code 2'", "LINE_PRCSG_IND_CD_2"),
        ("'Line Processing Indicator Code 3'", "LINE_PRCSG_IND_CD_3"),
        ("'Line Processing Indicator Code 4'", "LINE_PRCSG_IND_CD_4"),
        ("'Line Processing Indicator Code 5'", "LINE_PRCSG_IND_CD_5"),
        ("'Line Processing Indicator Code 6'", "LINE_PRCSG_IND_CD_6"),
        ("'Line Processing Indicator Code 7'", "LINE_PRCSG_IND_CD_7"),
        ("'Line Processing Indicator Code 8'", "LINE_PRCSG_IND_CD_8"),
        ("'Line Processing Indicator Code 9'", "LINE_PRCSG_IND_CD_9"),
        ("'Line Processing Indicator Code 10'", "LINE_PRCSG_IND_CD_10"),
        ("'Line Processing Indicator Code 11'", "LINE_PRCSG_IND_CD_11"),
        ("'Line Processing Indicator Code 12'", "LINE_PRCSG_IND_CD_12"),
        ("'Line Processing Indicator Code 13'", "LINE_PRCSG_IND_CD_13"),
        ("'Line Diagnosis Code 1'", "LINE_ICD9_DGNS_CD_1"),
        ("'Line Diagnosis Code 2'", "LINE_ICD9_DGNS_CD_2"),
        ("'Line Diagnosis Code 3'", "LINE_ICD9_DGNS_CD_3"),
        ("'Line Diagnosis Code 4'", "LINE_ICD9_DGNS_CD_4"),
        ("'Line Diagnosis Code 5'", "LINE_ICD9_DGNS_CD_5"),
        ("'Line Diagnosis Code 6'", "LINE_ICD9_DGNS_CD_6"),
        ("'Line Diagnosis Code 7'", "LINE_ICD9_DGNS_CD_7"),
        ("'Line Diagnosis Code 8'", "LINE_ICD9_DGNS_CD_8"),
        ("'Line Diagnosis Code 9'", "LINE_ICD9_DGNS_CD_9"),
        ("'Line Diagnosis Code 10'", "LINE_ICD9_DGNS_CD_10"),
        ("'Line Diagnosis Code 11'", "LINE_ICD9_DGNS_CD_11"),
        ("'Line Diagnosis Code 12'", "LINE_ICD9_DGNS_CD_12"),
        ("'Line Diagnosis Code 13'", "LINE_ICD9_DGNS_CD_13"),
        # Inpatients
        ("'Beneficiary Code'", "DESYNPUF_ID"),
        ("'Claim ID'", "CLM_ID"),
        ("'Provider institution'", "PRVDR_NUM"),
        ("'Attending Physician - National Provider Identifier Number'", "AT_PHYSN_NPI"),
        ("'Operating Physician - National Provider Identifier Number'", "OP_PHYSN_NPI"),
        ("'Other Physician - National Provider Identifier Number'", "OT_PHYSN_NPI"),
        ("'Claim Admitting Diagnosis Code'", "ADMTNG_ICD9_DGNS_CD"),
        ("'Claim Diagnosis Related Group Code'", "CLM_DRG_CD"),
        ("'Claim Diagnosis Code 1'", "ICD9_DGNS_CD_1"),
        ("'Claim Diagnosis Code 2'", "ICD9_DGNS_CD_2"),
        ("'Claim Diagnosis Code 3'", "ICD9_DGNS_CD_3"),
        ("'Claim Diagnosis Code 4'", "ICD9_DGNS_CD_4"),
        ("'Claim Diagnosis Code 5'", "ICD9_DGNS_CD_5"),
        ("'Claim Diagnosis Code 6'", "ICD9_DGNS_CD_6"),
        ("'Claim Diagnosis Code 7'", "ICD9_DGNS_CD_7"),
        ("'Claim Diagnosis Code 8'", "ICD9_DGNS_CD_8"),
        ("'Claim Diagnosis Code 9'", "ICD9_DGNS_CD_9"),
        ("'Claim Diagnosis Code 10'", "ICD9_DGNS_CD_10"),
        ("'Claim Procedure Code 1'", "ICD9_PRCDR_CD_1"),
        ("'Claim Procedure Code 2'", "ICD9_PRCDR_CD_2"),
        ("'Claim Procedure Code 3'", "ICD9_PRCDR_CD_3"),
        ("'Claim Procedure Code 4'", "ICD9_PRCDR_CD_4"),
        ("'Claim Procedure Code 5'", "ICD9_PRCDR_CD_5"),
        ("'Claim Procedure Code 6'", "ICD9_PRCDR_CD_6"),
        ("'Revenue Center HCFA Common Procedure Coding System 1'", "HCPCS_CD_1"),
        ("'Revenue Center HCFA Common Procedure Coding System 2'", "HCPCS_CD_2"),
        ("'Revenue Center HCFA Common Procedure Coding System 3'", "HCPCS_CD_3"),
        ("'Revenue Center HCFA Common Procedure Coding System 4'", "HCPCS_CD_4"),
        ("'Revenue Center HCFA Common Procedure Coding System 5'", "HCPCS_CD_5"),
        ("'Revenue Center HCFA Common Procedure Coding System 6'", "HCPCS_CD_6"),
        ("'Revenue Center HCFA Common Procedure Coding System 7'", "HCPCS_CD_7"),
        ("'Revenue Center HCFA Common Procedure Coding System 8'", "HCPCS_CD_8"),
        ("'Revenue Center HCFA Common Procedure Coding System 9'", "HCPCS_CD_9"),
        ("'Revenue Center HCFA Common Procedure Coding System 10'", "HCPCS_CD_10"),
        ("'Revenue Center HCFA Common Procedure Coding System 11'", "HCPCS_CD_11"),
        ("'Revenue Center HCFA Common Procedure Coding System 12'", "HCPCS_CD_12"),
        ("'Revenue Center HCFA Common Procedure Coding System 13'", "HCPCS_CD_13"),
        ("'Revenue Center HCFA Common Procedure Coding System 14'", "HCPCS_CD_14"),
        ("'Revenue Center HCFA Common Procedure Coding System 15'", "HCPCS_CD_15"),
        ("'Revenue Center HCFA Common Procedure Coding System 16'", "HCPCS_CD_16"),
        ("'Revenue Center HCFA Common Procedure Coding System 17'", "HCPCS_CD_17"),
        ("'Revenue Center HCFA Common Procedure Coding System 18'", "HCPCS_CD_18"),
        ("'Revenue Center HCFA Common Procedure Coding System 19'", "HCPCS_CD_19"),
        ("'Revenue Center HCFA Common Procedure Coding System 20'", "HCPCS_CD_20"),
        ("'Revenue Center HCFA Common Procedure Coding System 21'", "HCPCS_CD_21"),
        ("'Revenue Center HCFA Common Procedure Coding System 22'", "HCPCS_CD_22"),
        ("'Revenue Center HCFA Common Procedure Coding System 23'", "HCPCS_CD_23"),
        ("'Revenue Center HCFA Common Procedure Coding System 24'", "HCPCS_CD_24"),
        ("'Revenue Center HCFA Common Procedure Coding System 25'", "HCPCS_CD_25"),
        ("'Revenue Center HCFA Common Procedure Coding System 26'", "HCPCS_CD_26"),
        ("'Revenue Center HCFA Common Procedure Coding System 27'", "HCPCS_CD_27"),
        ("'Revenue Center HCFA Common Procedure Coding System 28'", "HCPCS_CD_28"),
        ("'Revenue Center HCFA Common Procedure Coding System 29'", "HCPCS_CD_29"),
        ("'Revenue Center HCFA Common Procedure Coding System 30'", "HCPCS_CD_30"),
        ("'Revenue Center HCFA Common Procedure Coding System 31'", "HCPCS_CD_31"),
        ("'Revenue Center HCFA Common Procedure Coding System 32'", "HCPCS_CD_32"),
        ("'Revenue Center HCFA Common Procedure Coding System 33'", "HCPCS_CD_33"),
        ("'Revenue Center HCFA Common Procedure Coding System 34'", "HCPCS_CD_34"),
        ("'Revenue Center HCFA Common Procedure Coding System 35'", "HCPCS_CD_35"),
        ("'Revenue Center HCFA Common Procedure Coding System 36'", "HCPCS_CD_36"),
        ("'Revenue Center HCFA Common Procedure Coding System 37'", "HCPCS_CD_37"),
        ("'Revenue Center HCFA Common Procedure Coding System 38'", "HCPCS_CD_38"),
        ("'Revenue Center HCFA Common Procedure Coding System 39'", "HCPCS_CD_39"),
        ("'Revenue Center HCFA Common Procedure Coding System 40'", "HCPCS_CD_40"),
        ("'Revenue Center HCFA Common Procedure Coding System 41'", "HCPCS_CD_41"),
        ("'Revenue Center HCFA Common Procedure Coding System 42'", "HCPCS_CD_42"),
        ("'Revenue Center HCFA Common Procedure Coding System 43'", "HCPCS_CD_43"),
        ("'Revenue Center HCFA Common Procedure Coding System 44'", "HCPCS_CD_44"),
        ("'Revenue Center HCFA Common Procedure Coding System 45'", "HCPCS_CD_45"),
        # Outpatients
        ("'Beneficiary Code'", "DESYNPUF_ID"),
        ("'Claim ID'", "CLM_ID"),
        ("'Provider institution'", "PRVDR_NUM"),
        ("'Attending Physician - National Provider Identifier Number'", "AT_PHYSN_NPI"),
        ("'Operating Physician - National Provider Identifier Number'", "OP_PHYSN_NPI"),
        ("'Other Physician - National Provider Identifier Number'", "OT_PHYSN_NPI"),
        ("'Claim Diagnosis Code 1'", "ICD9_DGNS_CD_1"),
        ("'Claim Diagnosis Code 2'", "ICD9_DGNS_CD_2"),
        ("'Claim Diagnosis Code 3'", "ICD9_DGNS_CD_3"),
        ("'Claim Diagnosis Code 4'", "ICD9_DGNS_CD_4"),
        ("'Claim Diagnosis Code 5'", "ICD9_DGNS_CD_5"),
        ("'Claim Diagnosis Code 6'", "ICD9_DGNS_CD_6"),
        ("'Claim Diagnosis Code 7'", "ICD9_DGNS_CD_7"),
        ("'Claim Diagnosis Code 8'", "ICD9_DGNS_CD_8"),
        ("'Claim Diagnosis Code 9'", "ICD9_DGNS_CD_9"),
        ("'Claim Diagnosis Code 10'", "ICD9_DGNS_CD_10"),
        ("'Claim Procedure Code 1'", "ICD9_PRCDR_CD_1"),
        ("'Claim Procedure Code 2'", "ICD9_PRCDR_CD_2"),
        ("'Claim Procedure Code 3'", "ICD9_PRCDR_CD_3"),
        ("'Claim Procedure Code 4'", "ICD9_PRCDR_CD_4"),
        ("'Claim Procedure Code 5'", "ICD9_PRCDR_CD_5"),
        ("'Claim Procedure Code 6'", "ICD9_PRCDR_CD_6"),
        ("'Claim Admitting Diagnosis Code'", "ADMTNG_ICD9_DGNS_CD"),
        ("'Revenue Center HCFA Common Procedure Coding System 1'", "HCPCS_CD_1"),
        ("'Revenue Center HCFA Common Procedure Coding System 2'", "HCPCS_CD_2"),
        ("'Revenue Center HCFA Common Procedure Coding System 3'", "HCPCS_CD_3"),
        ("'Revenue Center HCFA Common Procedure Coding System 4'", "HCPCS_CD_4"),
        ("'Revenue Center HCFA Common Procedure Coding System 5'", "HCPCS_CD_5"),
        ("'Revenue Center HCFA Common Procedure Coding System 6'", "HCPCS_CD_6"),
        ("'Revenue Center HCFA Common Procedure Coding System 7'", "HCPCS_CD_7"),
        ("'Revenue Center HCFA Common Procedure Coding System 8'", "HCPCS_CD_8"),
        ("'Revenue Center HCFA Common Procedure Coding System 9'", "HCPCS_CD_9"),
        ("'Revenue Center HCFA Common Procedure Coding System 10'", "HCPCS_CD_10"),
        ("'Revenue Center HCFA Common Procedure Coding System 11'", "HCPCS_CD_11"),
        ("'Revenue Center HCFA Common Procedure Coding System 12'", "HCPCS_CD_12"),
        ("'Revenue Center HCFA Common Procedure Coding System 13'", "HCPCS_CD_13"),
        ("'Revenue Center HCFA Common Procedure Coding System 14'", "HCPCS_CD_14"),
        ("'Revenue Center HCFA Common Procedure Coding System 15'", "HCPCS_CD_15"),
        ("'Revenue Center HCFA Common Procedure Coding System 16'", "HCPCS_CD_16"),
        ("'Revenue Center HCFA Common Procedure Coding System 17'", "HCPCS_CD_17"),
        ("'Revenue Center HCFA Common Procedure Coding System 18'", "HCPCS_CD_18"),
        ("'Revenue Center HCFA Common Procedure Coding System 19'", "HCPCS_CD_19"),
        ("'Revenue Center HCFA Common Procedure Coding System 20'", "HCPCS_CD_20"),
        ("'Revenue Center HCFA Common Procedure Coding System 21'", "HCPCS_CD_21"),
        ("'Revenue Center HCFA Common Procedure Coding System 22'", "HCPCS_CD_22"),
        ("'Revenue Center HCFA Common Procedure Coding System 23'", "HCPCS_CD_23"),
        ("'Revenue Center HCFA Common Procedure Coding System 24'", "HCPCS_CD_24"),
        ("'Revenue Center HCFA Common Procedure Coding System 25'", "HCPCS_CD_25"),
        ("'Revenue Center HCFA Common Procedure Coding System 26'", "HCPCS_CD_26"),
        ("'Revenue Center HCFA Common Procedure Coding System 27'", "HCPCS_CD_27"),
        ("'Revenue Center HCFA Common Procedure Coding System 28'", "HCPCS_CD_28"),
        ("'Revenue Center HCFA Common Procedure Coding System 29'", "HCPCS_CD_29"),
        ("'Revenue Center HCFA Common Procedure Coding System 30'", "HCPCS_CD_30"),
        ("'Revenue Center HCFA Common Procedure Coding System 31'", "HCPCS_CD_31"),
        ("'Revenue Center HCFA Common Procedure Coding System 32'", "HCPCS_CD_32"),
        ("'Revenue Center HCFA Common Procedure Coding System 33'", "HCPCS_CD_33"),
        ("'Revenue Center HCFA Common Procedure Coding System 34'", "HCPCS_CD_34"),
        ("'Revenue Center HCFA Common Procedure Coding System 35'", "HCPCS_CD_35"),
        ("'Revenue Center HCFA Common Procedure Coding System 36'", "HCPCS_CD_36"),
        ("'Revenue Center HCFA Common Procedure Coding System 37'", "HCPCS_CD_37"),
        ("'Revenue Center HCFA Common Procedure Coding System 38'", "HCPCS_CD_38"),
        ("'Revenue Center HCFA Common Procedure Coding System 39'", "HCPCS_CD_39"),
        ("'Revenue Center HCFA Common Procedure Coding System 40'", "HCPCS_CD_40"),
        ("'Revenue Center HCFA Common Procedure Coding System 41'", "HCPCS_CD_41"),
        ("'Revenue Center HCFA Common Procedure Coding System 42'", "HCPCS_CD_42"),
        ("'Revenue Center HCFA Common Procedure Coding System 43'", "HCPCS_CD_43"),
        ("'Revenue Center HCFA Common Procedure Coding System 44'", "HCPCS_CD_44"),
        ("'Revenue Center HCFA Common Procedure Coding System 45'", "HCPCS_CD_45"),
        # Prescription
        ("'Beneficiary Code'", "DESYNPUF_ID"),
        ("'CCW Part D Event Number'", "PDE_ID"),
        ("'Product Service ID'", "PROD_SRVC_ID"),
    ]

    # Edit numerical_operators to adapt to new set of numerical operators.
    numerical_operators = [
        ("equal to", "="),
        ("less than", "<"),
        ("less than or equal to", "<="),
        ("greater than", ">"),
        ("greater than or equal to", ">="),
    ]
    # Sort for the longest match ("less than" versus "less than or equal to")
    numerical_operators = sorted(numerical_operators, \
                                 key=lambda t: len(t[0]), \
                                 reverse=True)

    # Edit digits to adapt to new set of digits.
    digits = "0123456789"

    # Edit characters to adapt to new set of characters.
    characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._*%-"
